---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base

inputs:
  - name: version
  - name: tools
  - name: repo

outputs:
  - name: updated-version

run:
  path: repo/ci/tasks/get-version/task.sh
